#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail

# TODO: Install logs should be stored somewhere and not sent to stdout/err
echo ""

# Current path
cwd=$(pwd) 

# SANITY CHECKS:
# Cuda variables set
if [ -z $CUDA_HOME ];then
    printf "You need to define CUDA variables in ~/.bash_profile, see README"
    exit
fi
# This is launched from the correct folder
if [ "$(basename $cwd)" != "tools" ];then
    printf "\n$0 should be called from inside the espnet/tools folder\n\n"    
    exit
fi

##############################################################################
#                                KALDI
##############################################################################
# Note that you can link your kaldi installation int the folder to skip this
# step ln -s /my/kaldi/ kaldi
if [ ! -f "kaldi/src/featbin/copy-feats" ];then
    
    # Download kaldi        
    if [ ! -f "kaldi_github" ];then
        git clone https://github.com/kaldi-asr/kaldi.git kaldi_github    
    else:
        printf "\033[92mFound\033[0m downloaded kaldi_github\n"
    fi

    # Try installation
	cd kaldi_github/tools
    make all
	cd ../src
    ./configure --shared --use-cuda=no
    make depend
    make all
    if [ ! -f "kaldi/src/featbin/copy-feats" ];then
	    ln -s kaldi_github kaldi
    else    
        printf "Automatic Kaldi installation \033[31mFailed\033[0m\n"            
        printf "See kaldi_github/INSTALL for manual instructions\n"            
    fi

else
    printf "\033[92mFound\033[0m installed kaldi\n"
fi
cd $cwd
# Get extra io tools for Kaldi
if [ ! -f "../src/utils/kaldi_io_py.py" ];then
    git clone https://github.com/vesis84/kaldi-io-for-python.git
    cd ../src/utils
    ln -s ../../tools/kaldi-io-for-python/kaldi_io.py kaldi_io_py.py
    if [ ! -f "kaldi_io_py.py" ];then
        printf "Installing kaldi io \033[31mFailed\033[0m (Internet?)\n"            
        exit            
    fi
else
    printf "\033[92mFound\033[0m installed kaldi_io_py.py\n"
fi
cd $cwd

##############################################################################
#                               NKF 
##############################################################################
if [ ! -f "nkf/nkf-2.1.4/nkf" ] ;then
    mkdir -p nkf
    cd nkf
    wget http://gigenet.dl.osdn.jp/nkf/64158/nkf-2.1.4.tar.gz
    tar zxvf nkf-2.1.4.tar.gz
    cd nkf-2.1.4
    make prefix=.
    if [ ! -f "nkf" ] ;then
        printf "Installing nkf \033[31mFailed\033[0m\n"
    fi
else
    printf "\033[92mFound\033[0m installed nkf\n"
fi
cd $cwd

# Python territory check for condaenv 
set +o nounset
# Sanity Check: novirtualenv 
if [ ! -z $VIRTUAL_ENV ];then
    printf "\nThis is for a conda environment not a virtualenv!\n"
    exit
fi
if [ "$CONDA_DEFAULT_ENV" == "" ];then
    printf "\nFor the Python modules, use a conda environment, for example\n\n"
    printf "conda create -n py27_test python=2.7 --yes\n"
    printf "conda activate py27_test\n"
    printf "bash install_with_conda\n\n"
    exit        
fi
set -o nounset

# Python2 
if [  "$(python -c 'import sys; print(sys.version_info[0:2])')" != "(2, 7)" ];then
    printf "\nExpected virtualenv with Python 2.7 (conda create -n py27_test python=2.7 --yes)\n\n"
    exit
fi


# Install Python modules
conda install chainer>=3.0.0 --yes
conda install -c contango python_speech_features --yes
conda install numpy pyyaml mkl mkl-include setuptools cmake cffi typing cython --yes

# KARTHICKS TRICK
pip install cupy-cuda90 --pre
conda install -c pytorch magma-cuda90

# Pytorch
# KARTHICKS TRICK
pip install torch==0.3.1
pip install torchvision

##############################################################################
#                              CTC 
##############################################################################


# Warp-CTC
# Download warp-ctc 
if [ -d "warp-ctc" ];then
    rm -rf warp-ctc        
fi
git clone https://github.com/SeanNaren/warp-ctc.git
cd warp-ctc
git checkout 9e5b238f8d9337b0c39b3fd01bbaff98ba523aa5
mkdir build
cd build 
cmake .. 
make -j4
cd ../pytorch_binding
python setup.py install
cd $cwd

if [ -d "chainer_ctc" ];then
    rm -rf chainer_ctc    
fi
git clone https://github.com/jheymann85/chainer_ctc.git
cd chainer_ctc 
chmod +x install_warp-ctc.sh 
./install_warp-ctc.sh 
pip install .
cd $cwd

# Sanity check
python -c "import torch;torch.cuda.is_available()"
python -c "import warpctc_pytorch"
